### ISSUE TITLE
可否说明完整的删除 "tags和taggings这两个表，和其相关的索引" 步骤?

### ISSUE THREAD

**Issue by uart-aplex** [lornwolf/redmine_knowledgebase#1]
为避免破坏资料库的完整性, 可否给个MYSQL操作指令范例来做这个操作?
谢谢.

**Comment by lornwolf** [comment]
DROP TABLE tags;
DROP TABLE taggings;

**Comment by uart-aplex** [comment]
谢谢, 我前面以为也要DROP INDEX.

**Comment by lornwolf** [comment]
删表的时候，index应该会被自动删除了吧。

**Comment by uart-aplex** [comment]
我删除了这两个table后, 然后安装你的KM, 
bundle install
rake redmine:plugins:migrate NAME=redmine_knowledgebase RAILS_ENV=production

装完之后database并没有重新产生这两个表, 且redmine重启后网页也打不开了, 
We're sorry, but something went wrong.
The issue has been logged for investigation. Please try again later.

要如何重新产生这两个表?

**Comment by lornwolf** [comment]
看看log里出的什么错误信息？

**Comment by uart-aplex** [comment]
我重做一次, 以便记录错误讯息, 发现删除掉tags, taggiings后, 安装你的KM就会出错, 似乎你的KM并不会重taggings表就直接要去建索引, 缺了表就去建索引所以出错.

有什么办法去重建这taggiings表吗?

 rake redmine:plugins:migrate NAME=redmine_knowledgebase RAILS_ENV=production
== 20150326093139 AddMissingTaggableIndex: migrating ==========================
-- add_index(:taggings, [:taggable_id, :taggable_type, :context])
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'bitnami_redmine.taggings' doesn't exist: CREATE  INDEX `index_taggings_on_taggable_id_and_taggable_type_and_context`  ON `taggings` (`taggable_id`, `taggable_type`, `context`) 
~/redmine-4.1.1-3/apps/redmine/htdocs/plugins/redmine_knowledgebase/db/migrate/20150326093139_add_missing_taggable_index.rb:3:in `up'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:510:in `up'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:542:in `migrate_plugin'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:483:in `migrate'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:494:in `migrate'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'bitnami_redmine.taggings' doesn't exist: CREATE  INDEX `index_taggings_on_taggable_id_and_taggable_type_and_context`  ON `taggings` (`taggable_id`, `taggable_type`, `context`) 
~/redmine-4.1.1-3/apps/redmine/htdocs/plugins/redmine_knowledgebase/db/migrate/20150326093139_add_missing_taggable_index.rb:3:in `up'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:510:in `up'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:542:in `migrate_plugin'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:483:in `migrate'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:494:in `migrate'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'

Caused by:
Mysql2::Error: Table 'bitnami_redmine.taggings' doesn't exist
~/redmine-4.1.1-3/apps/redmine/htdocs/plugins/redmine_knowledgebase/db/migrate/20150326093139_add_missing_taggable_index.rb:3:in `up'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:510:in `up'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:542:in `migrate_plugin'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:483:in `migrate'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:494:in `migrate'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

**Comment by uart-aplex** [comment]
还是只能删除tags, 不要删除taggings? 待会这样试看看.

**Comment by uart-aplex** [comment]
只刪除tags, 沒刪除taggings, 然後安裝你的KM依然出錯:

rake redmine:plugins:migrate NAME=redmine_knowledgebase RAILS_ENV=production
== 20150326093139 AddMissingTaggableIndex: migrating ==========================
-- add_index(:taggings, [:taggable_id, :taggable_type, :context])
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Key column 'context' doesn't exist in table: CREATE  INDEX `index_taggings_on_taggable_id_and_taggable_type_and_context`  ON `taggings` (`taggable_id`, `taggable_type`, `context`) 
~/redmine-4.1.1-3/apps/redmine/htdocs/plugins/redmine_knowledgebase/db/migrate/20150326093139_add_missing_taggable_index.rb:3:in `up'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:510:in `up'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:542:in `migrate_plugin'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:483:in `migrate'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:494:in `migrate'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Key column 'context' doesn't exist in table: CREATE  INDEX `index_taggings_on_taggable_id_and_taggable_type_and_context`  ON `taggings` (`taggable_id`, `taggable_type`, `context`) 
~/redmine-4.1.1-3/apps/redmine/htdocs/plugins/redmine_knowledgebase/db/migrate/20150326093139_add_missing_taggable_index.rb:3:in `up'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:510:in `up'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:542:in `migrate_plugin'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:483:in `migrate'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:494:in `migrate'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'

Caused by:
Mysql2::Error: Key column 'context' doesn't exist in table
~/redmine-4.1.1-3/apps/redmine/htdocs/plugins/redmine_knowledgebase/db/migrate/20150326093139_add_missing_taggable_index.rb:3:in `up'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:510:in `up'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:542:in `migrate_plugin'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:483:in `migrate'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/redmine/plugin.rb:494:in `migrate'
~/redmine-4.1.1-3/apps/redmine/htdocs/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

**Comment by lornwolf** [comment]
create table taggings
(
	id int4 default nextval('taggings_id_seq1'::regclass) not null
		constraint taggings_pkey1
			primary key,
	tag_id int4
		constraint fk_rails_9fcd2e236b
			references tags,
	taggable_type varchar,
	taggable_id int4,
	tagger_type varchar,
	tagger_id int4,
	context varchar(128),
	created_at timestamp(6),
	constraint taggings_idx
		unique (tag_id, taggable_id, taggable_type, context, tagger_id, tagger_type)
);

create index index_taggings_on_taggable_id_and_taggable_type_and_context
	on taggings (taggable_id, taggable_type, context);

create index taggings_taggable_context_idx
	on taggings (taggable_id, taggable_type, context);

create table tags
(
	id int4 default nextval('tags_id_seq1'::regclass) not null
		constraint tags_pkey1
			primary key,
	name varchar
		constraint index_tags_on_name
			unique,
	created_at timestamp(6),
	updated_at timestamp(6),
	taggings_count int4 default 0
);

这是我从我的数据库里导出来的。
按说在安装这个插件时，这两个表会自动创建的（20130513154700_add_tags_and_taggings.rb）。
