### ISSUE TITLE
请问有兼容最新的Redmine 4.1.1版吗?

### ISSUE THREAD

**Issue by uart-aplex** [lornwolf/redmine_knowledgebase#2]
看起来这插件原本来源不兼容Redmine 4.1.x, 直到最近作者才更新可兼容4.1.x的问题, 不知你这一版有没有兼容Redmine 4.1.x?

**Comment by lornwolf** [comment]
我只有一个4.0.x的环境，没在4.1.x上试过。
如果原作者更新了，用他的最好，我这一版也没做什么太大改动。

**Comment by uart-aplex** [comment]
不过原作者没解决跟RedmineUP一些插件不兼容的问题....就是更新后一样使用tags, taggings table.

**Comment by lornwolf** [comment]
冲突的解决方法很简单。

一、viewings表已经存在。

这个表是redmine_question插件创建的，redmine_knowledge也要创建同名的一个表。

解决方法：用查找替换的方法，把redmine_knowledge插件源代码中的viewings全部替换成viewinges。

二、说是tags和taggings这两个表已经存在，但是与预想的结构不一致。

这两个表是redmineup_tags插件安装时创建的，这两个插件都用到了同一个Gem包，但创建的表结构却不一致。

解决方法：

手动从数据库中删掉这两个表，再安装redmine_knowledge。

由redmine_knowledge生成的tags和taggings表，tags插件也能用，所以两个插件可以共存。

**Comment by uart-aplex** [comment]
再请教一下. 
我没有安装redmine_tags插件, 那是否只要改KM插件内的viewings便可?

**Comment by lornwolf** [comment]
代码里我都改好了，直接clone下来用就可以了。

**Comment by uart-aplex** [comment]
哈, 太感谢了, 我对ruby语言软件不熟...其实也只会用, 不懂自己去写软件...

**Comment by lornwolf** [comment]
我对ruby也是完全不会，硬改的。
